# Generated by Django 3.1.7 on 2021-05-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210402_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='landing_page',
            field=models.BooleanField(default=False),
        ),
    ]
